# quick-start guide used https://docs.github.com/en/actions/writing-workflows/quickstart

name: Run run-tests.py on Push

# trigger workflow after push 
on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest  

    steps:
      # access code
      - name: Checkout code
        uses: actions/checkout@v3

      # set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11 

      # install dependencies 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies.txt

      # run tests
      - name: Run data-visualisation-test.py
        run: |
          cd ../scripts/test/
          python ../scripts/test/data-visualisation-test.py
